// <auto-generated />
namespace Search.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class may1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(may1));
        
        string IMigrationMetadata.Id
        {
            get { return "201305012255448_may1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
