// <auto-generated />
namespace Search.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class May3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(May3));
        
        string IMigrationMetadata.Id
        {
            get { return "201305031735059_May3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
